# Generated by Django 5.2.4 on 2025-07-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='location',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
