# Generated by Django 5.2.4 on 2025-07-16 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_touristplace_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='touristplace',
            name='created_at',
        ),
        migrations.AddField(
            model_name='touristplace',
            name='visit_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
