# Generated by Django 5.2.4 on 2025-07-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristplace',
            name='entry_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.FloatField(),
        ),
    ]
