# Generated by Django 5.2.4 on 2025-07-16 13:15

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_touristplace_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristplace',
            name='number_of_ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='sum_of_ratings',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AddField(
            model_name='touristplace',
            name='total_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='entry_fee',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='location',
            field=models.CharField(default='Not specified', max_length=255),
        ),
        migrations.AlterField(
            model_name='touristplace',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
