# Generated by Django 5.2.4 on 2025-07-16 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_touristplace_number_of_ratings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to='places.touristplace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration_days',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='guide',
            field=models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='tour_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
